### ISSUE TITLE
Unable to download model

### ISSUE THREAD

**Issue by talhaanwarch** [hfawaz/bigdata18#4]
Greetings. I am curious to know that these time series pretrained model can diagnose normal vs disease patients using EEG. But i am unable to download the model. Link on https://germain-forestier.info/src/bigdata2018/ site is not working. Please check it

**Comment by forestier** [comment]
Hi @talhaanwarch ,

Thank you for your interest in our work.

https://germain-forestier.info is hosted on a shared hosting service.

It can happend that the IP of the server is banned by your ISP because other users using the same IP performed malicious activities.

This is unfortunate and we do not control it. We are in the process of finding a fix.

As a short term fix, please try to connect to the website using an alternative ISP (not from your University but using your cell phone or your home connection).

Let me know if you managed to connect to the website using another ISP.

Please let me know about the network causing problem, it will help us to find a fix.

Best,

Germain

**Comment by talhaanwarch** [comment]
hi @forestier  actually this website is not working
http://supplementarymaterial.xyz/bigdata2018/fine-tuned-models-part-1.tar.gz
https://germain-forestier.info/src/bigdata2018/ this website is working

**Comment by forestier** [comment]
Hi @talhaanwarch ,

The problem should be fixed now.

Could you try again ?

Sorry for the inconvenience, thanks for pointing it out.

Best,

Germain

**Comment by talhaanwarch** [comment]
Yes, i have tried even in incognito mode (to avoid cache stuff) and problem is still there

**Comment by forestier** [comment]
http://supplementarymaterial.xyz/ was actually deactivated.

I reactivated it but it could take a few hours to be fully available all around the world.

Wait a bit and try again and let me know.

Best,

Germain

**Comment by talhaanwarch** [comment]
thanks, its working now
